-- Auto-generated by sync-theme.py — do not edit directly
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "synced"

local colors = {
  bg = "#1e1e2e", fg = "#cdd6f4",
  black = "#45475a", red = "#f38ba8", green = "#a6e3a1",
  yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7",
  cyan = "#94e2d5", white = "#bac2de",
  bright_black = "#585b70", bright_red = "#f38ba8",
}

vim.g.terminal_color_0 = "#45475a"
vim.g.terminal_color_1 = "#f38ba8"
vim.g.terminal_color_2 = "#a6e3a1"
vim.g.terminal_color_3 = "#f9e2af"
vim.g.terminal_color_4 = "#89b4fa"
vim.g.terminal_color_5 = "#f5c2e7"
vim.g.terminal_color_6 = "#94e2d5"
vim.g.terminal_color_7 = "#bac2de"
vim.g.terminal_color_8 = "#585b70"
vim.g.terminal_color_9 = "#f38ba8"
vim.g.terminal_color_10 = "#a6e3a1"
vim.g.terminal_color_11 = "#f9e2af"
vim.g.terminal_color_12 = "#89b4fa"
vim.g.terminal_color_13 = "#f5c2e7"
vim.g.terminal_color_14 = "#94e2d5"
vim.g.terminal_color_15 = "#a6adc8"

local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

hi("Normal", { fg = colors.fg, bg = colors.bg })
hi("Comment", { fg = colors.bright_black, italic = true })
hi("Constant", { fg = colors.magenta })
hi("String", { fg = colors.green })
hi("Identifier", { fg = colors.blue })
hi("Function", { fg = colors.blue })
hi("Statement", { fg = colors.red })
hi("Keyword", { fg = colors.red })
hi("PreProc", { fg = colors.yellow })
hi("Type", { fg = colors.yellow })
hi("Special", { fg = colors.cyan })
hi("CursorLine", { bg = colors.black })
hi("Visual", { bg = colors.bright_black })
hi("LineNr", { fg = colors.bright_black })
hi("Pmenu", { fg = colors.fg, bg = colors.black })
hi("PmenuSel", { fg = colors.bg, bg = colors.blue })
hi("StatusLine", { fg = colors.fg, bg = colors.black })
hi("VertSplit", { fg = colors.black })
hi("Search", { fg = colors.bg, bg = colors.yellow })
hi("IncSearch", { fg = colors.bg, bg = colors.red })
hi("DiffAdd", { fg = colors.green })
hi("DiffDelete", { fg = colors.red })
hi("DiffChange", { fg = colors.yellow })
